### ISSUE TITLE
Fall back images show up on profile

### ISSUE THREAD

**Issue by akshay-patel-y** [lens-protocol/lens-widgets#3]
Would it be possible to add the fall back images that show up on lenster onto the profile widget

lenster: 
![image](https://user-images.githubusercontent.com/59624240/225447410-63295963-ac8c-4696-8e13-f0b0b812026d.png)
Profile widget curr:
![image](https://user-images.githubusercontent.com/59624240/225447437-9905758d-070b-4507-9b08-74ba0b26f055.png)

**Comment by dabit3** [comment]
thanks @akshay-patel-y this has now been fixed in the React package
