### ISSUE TITLE
Hide follow button to allow for creator/fan side configuration

### ISSUE THREAD

**Issue by akshay-patel-y** [lens-protocol/lens-widgets#4]
Would it be possible to hide the follow button from lens settings page so we could have it configuration for creators and fans be diff
This can allow us to hide the follow if a creator is looking at it and change the display for a fan
![image](https://user-images.githubusercontent.com/59624240/225447602-648c4c05-6e09-4789-86fd-b4d8e0e859d6.png)

**Comment by dabit3** [comment]
Thanks @akshay-patel-y this is now part of the library
