### ISSUE TITLE
SigninWidget Error handling

### ISSUE THREAD

**Issue by akshay-patel-y** [lens-protocol/lens-widgets#5]
Would it be possible to return an "error" variable so we can handle the proper handling of the cases where a user does not have a lens profile/render the correct UI for these cases. On some instances, we noticed that the signing in working after refreshes of the page or also there was no good way to handle if a user had an account or not through lens. So it would be great if in addition to profile, and token, we could return some indication of error so it can be handled on the client side. Thanks!
errors such as these
<img width="463" alt="image" src="https://user-images.githubusercontent.com/59624240/225567512-040e6be2-a832-429c-8cf7-f1461e6ca95c.png">

**Comment by dabit3** [comment]
thanks @akshay-patel-y this has been added
