### ISSUE TITLE
Unable to Sign Out

### ISSUE THREAD

**Issue by bartomolina** [lens-protocol/lens-widgets#6]
I'm using the Sign in With Lens component in a Next.js application and I'm storing the auth token in the session storage.

I'm trying to Sign Out by just removing the session storage:

```
const logout = (event: FormEvent) => {
  event.preventDefault();
  window.sessionStorage.removeItem("lens-auth-token");
  setAuthToken("");
  setProfile({});
};
```

However, when I try to Sign In again, I'm getting the following error:

```
error signing in with Lens... TypeError: Cannot read properties of null (reading 'authenticate')
  at eval (SignInWithLens.js?b03f:123:50)
  at step (SignInWithLens.js?b03f:43:23)
  at Object.eval [as next] (SignInWithLens.js?b03f:24:53)
  at fulfilled (SignInWithLens.js?b03f:15:58)
```

I've also tried calling the `useDisconnect` hook from wagmi, but still getting the same error. Is it possible to disconnect the session somehow?

**Comment by dabit3** [comment]
hey, the library does not deal with storing any tokens it is up to you to handle, that being said I'd be happy to help debug. are you still having issues here?

**Comment by bartomolina** [comment]
Thanks Nader! I'm using the API / SDK and I got it working now.
